import {
  AddIcon,
  ArrowBackIcon,
  ArrowDownIcon,
  ArrowForwardIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  AtSignIcon,
  AttachmentIcon,
  BellIcon,
  CalendarIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CopyIcon,
  DeleteIcon,
  DownloadIcon,
  DragHandleIcon,
  EditIcon,
  EmailIcon,
  ExternalLinkIcon,
  HamburgerIcon,
  InfoIcon,
  InfoOutlineIcon,
  LinkIcon,
  LockIcon,
  MinusIcon,
  MoonIcon,
  NotAllowedIcon,
  PhoneIcon,
  PlusSquareIcon,
  QuestionIcon,
  QuestionOutlineIcon,
  RepeatClockIcon,
  RepeatIcon,
  Search2Icon,
  SearchIcon,
  SettingsIcon,
  SmallAddIcon,
  SmallCloseIcon,
  SpinnerIcon,
  StarIcon,
  SunIcon,
  TimeIcon,
  TriangleDownIcon,
  TriangleUpIcon,
  UnlockIcon,
  UpDownIcon,
  ViewIcon,
  ViewOffIcon,
  WarningIcon,
  WarningTwoIcon,
} from "@chakra-ui/icons";

let iconList = [
  {"id": 0, "icon": CopyIcon},
  {"id": 1, "icon": SearchIcon},
  {"id": 2, "icon": Search2Icon},
  {"id": 3, "icon": MoonIcon},
  {"id": 4, "icon": SunIcon},
  {"id": 5, "icon": AddIcon},
  {"id": 6, "icon": SmallAddIcon},
  {"id": 7, "icon": SettingsIcon},
  {"id": 8, "icon": CheckCircleIcon},
  {"id": 9, "icon": LockIcon},
  {"id": 10, "icon": UnlockIcon},
  {"id": 11, "icon": ViewIcon},
  {"id": 12, "icon": ViewOffIcon},
  {"id": 13, "icon": DownloadIcon},
  {"id": 14, "icon": DeleteIcon},
  {"id": 15, "icon": RepeatIcon},
  {"id": 16, "icon": RepeatClockIcon},
  {"id": 17, "icon": EditIcon},
  {"id": 18, "icon": ChevronLeftIcon},
  {"id": 19, "icon": ChevronRightIcon},
  {"id": 20, "icon": ChevronDownIcon},
  {"id": 21, "icon": ChevronUpIcon},
  {"id": 22, "icon": ArrowBackIcon},
  {"id": 23, "icon": ArrowForwardIcon},
  {"id": 24, "icon": ArrowUpIcon},
  {"id": 25, "icon": ArrowUpDownIcon},
  {"id": 26, "icon": ArrowDownIcon},
  {"id": 27, "icon": ExternalLinkIcon},
  {"id": 28, "icon": LinkIcon},
  {"id": 29, "icon": PlusSquareIcon},
  {"id": 30, "icon": CalendarIcon},
  {"id": 31, "icon": ChatIcon},
  {"id": 32, "icon": TimeIcon},
  {"id": 33, "icon": ArrowRightIcon},
  {"id": 34, "icon": ArrowLeftIcon},
  {"id": 35, "icon": AtSignIcon},
  {"id": 36, "icon": AttachmentIcon},
  {"id": 37, "icon": UpDownIcon},
  {"id": 38, "icon": StarIcon},
  {"id": 39, "icon": EmailIcon},
  {"id": 40, "icon": PhoneIcon},
  {"id": 41, "icon": DragHandleIcon},
  {"id": 42, "icon": SpinnerIcon},
  {"id": 43, "icon": CloseIcon},
  {"id": 44, "icon": SmallCloseIcon},
  {"id": 45, "icon": NotAllowedIcon},
  {"id": 46, "icon": TriangleDownIcon},
  {"id": 47, "icon": TriangleUpIcon},
  {"id": 48, "icon": InfoOutlineIcon},
  {"id": 49, "icon": BellIcon},
  {"id": 50, "icon": InfoIcon},
  {"id": 51, "icon": QuestionIcon},
  {"id": 52, "icon": QuestionOutlineIcon},
  {"id": 53, "icon": WarningIcon},
  {"id": 54, "icon": WarningTwoIcon},
  {"id": 55, "icon": CheckIcon},
  {"id": 56, "icon": MinusIcon},
  {"id": 57, "icon": HamburgerIcon},
]

// for multiple icons
// const iconList = [...iconList, ...iconList, ...iconList, ...iconList].slice(0, 200)

export default iconList;